# Generated by Django 3.2.3 on 2021-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khyuser', '0002_khyuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khyuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
